//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCStock.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;


    public partial class TBL_Customers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_Customers()
        {
            this.TBL_Sales = new HashSet<TBL_Sales>();
        }
    
        public int Customer_Id { get; set; }

        [Required(ErrorMessage ="You Cannot Leave This Field Blank !!!")]
        [StringLength(50,ErrorMessage = "Enter a Maximum of 50 characters in This Field :)")]
        public string Name { get; set; }

        [Required(ErrorMessage = "You Cannot Leave This Field Blank !!!")]
        [StringLength(50, ErrorMessage = "Enter a Maximum of 50 characters in This Field :)")]
        public string Surname { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Sales> TBL_Sales { get; set; }
    }
}
